name: NMLArmor
version: '1.0'
main: io.github.NoOne.nMLArmor.NMLArmor
api-version: '1.21'
depend:
  - NMLPlayerStats
  - NMLDefenses
  - NMLItems
commands:
  generateArmor:
    description: generates a piece of armor for the player
    usage: /<command> <type> <rarity>